//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmdletTesting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmdletTesting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;sample&gt;
        ///  &lt;container name=&quot;deleteable&quot; shouldBeDeleted=&quot;true&quot;&gt;
        ///    &lt;policy name=&quot;mypolicy&quot; minus=&quot;1&quot;/&gt;
        ///
        ///  &lt;/container&gt;
        ///  &lt;container name=&quot;not_deleteable&quot; shouldBeDeleted=&quot;false&quot;&gt;
        ///    &lt;policy name=&quot;mypolicy&quot; minus=&quot;1&quot;/&gt;
        ///
        ///  &lt;/container&gt;
        ///
        ///  &lt;container name=&quot;deletable_something&quot; shouldBeDelete=&quot;false&quot;&gt;
        ///    &lt;policy name=&quot;mypolicy&quot; minus=&quot;1&quot;/&gt;
        ///
        ///  &lt;/container&gt;
        ///
        ///  &lt;container name=&quot;deletable&quot; shouldBeDelete=&quot;false&quot;&gt;
        ///    &lt;policy name=&quot;somethingother_mypolicy&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleDataForDeleting {
            get {
                return ResourceManager.GetString("SampleDataForDeleting", resourceCulture);
            }
        }
    }
}
